### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by Mohammad-debug** [angelvillar96/MSPred#1]
Hi,
I am computer science student and working on predicting motion of human organs. I was curious to test MSPred on our datatset. I would like to know the steps I need to take to run it on my datasets. My dataset consist of 300 frames of 80x80 taken at interval of 1 seconds.    

Thanks,
Mohammad

**Comment by angelvillar96** [comment]
Hi Mohammad,

It seems like the videos you plan to work with differ significantly from those MSPred was trained on (MovingMNIST, KTH, and Synpick).
Due to this large domain gap, I do not expect MSPred to perform too well on your data without any fine-tuning on that same domain.

In any case, if you want to try it, the steps are as follows:

1.  Create your dataset module in a new file in `src/data`. For instance  `src/data/organs.py`.
2.  Add your dataset in `src/data/__init__.py`. For example:  `from .organs import organs`
3. Support loading your dataset in `src/data/load_data.py` in function `load_data`.
4. Add the name of your dataset in `src/CONFIG.py` in the DATASETS list

The steps above allow you to support using a new dataset.
To train/evaluate a model, follow the README.md instructions for creating and training/evaluating an experiment.

Do not hesitate to let me know if you encounter problems of have any further questions.
Best,
Angel
